### PR TITLE
Implementation of Threefish complete

### PR DESCRIPTION
**Pull request by niluxv**
https://github.com/DaGenix/rust-crypto/pull/400

### CODE REVIEW

**Comment by notgne2** [comment]
Is this fully working? I'd really like to see a skein hash implementation finished too.

**Comment by niluxv** [comment]
All tests pass. I haven't looked into the implementation much though.

**Comment by niluxv** [comment]
Looks like RustCrypto [is going to implement skein](https://github.com/RustCrypto/hashes/pull/47).
If you didn't use rust-crypto I would recommend you use [RustCrypto](https://github.com/RustCrypto) anyway.
rust-crypto-maintained is useful when you have a project using rust-crypto already, because you do not need to make any changes to your code.

**Comment by notgne2** [comment]
Ah perfect, thanks! I wasn't already using rust-crypto, I just found the original repository looking for a skein hash implementation and found this as an active fork. I hope that implementation works.

**Pull request merged**
